name: hive-chat
version: '1.2.0'
main: me.levitate.hiveChat.HiveChat
api-version: '1.20'
authors: [ Levitate ]
description: A library for handling Minecraft messages in a more powerful and intuitive manner.
folia-supported: true